version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: smart_grid_broker
    ports:
      - "0.0.0.0:1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf